### ISSUE TITLE
ROS interface for perceiving objects in pancake scenario

### ISSUE THREAD

**Issue by airballking** [code-iai/iai_common_msgs#6]
@bbferka and me want to work out the details of a ROS interface for perceiving objects in the pancake scenario. This shall be a place where we document our discussions and decisions.

**Comment by fairlight1337** [comment]
I think this is long overdue to be closed. Lots of changes happened to [designator_integration](http://github.com/code-iai/designator_integration) since then. @airballking, did we solve the point of this issue? Its been open for almost two years.

**Comment by airballking** [comment]
@fairlight1337 I guess the issue evolved in the meantime. ;) I think we can close this.
